### ISSUE TITLE
Login omöjlig

### ISSUE THREAD

**Issue by Raket69** [mathiastornblom/net.tornbloms.deco#1]
Hej. Chansar på svenska utifrån ditt namn.
Jag försöker att ansluta till min router med ip-adress och lösenord, men får tillbaka att det är fel. Är det jag eller appen?

Med vänlig hälsning

Peter Hammarberg

**Comment by FredStang** [comment]
Får feilmelding når jeg prøver å logge inn.

"De oppgitte brukeropplysningene er ugyldige". 

Jeg vet at brukernavn og passord er riktig, da jeg har testet mot deco appen på telefon.

**Comment by mathiastornblom** [comment]
Could you try using the web browser to log in to the router? Does this login work for you? The username is fixed in the Decos. You use the same password to log in to the Deco app, and the IP is the router's IP. Generally, you can use tplinkdeco.net as the hostname/IP if you don't know it.

**Comment by FredStang** [comment]
@mathiastornblom That worked perfectly! Thank you 🙏😃

**Comment by mathiastornblom** [comment]
Thanks, right details works
